# Generated by Django 5.2 on 2025-06-05 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mod_id', models.TextField(default='')),
                ('steam_workshop_link', models.TextField(default='')),
                ('mod_title', models.TextField(default='')),
                ('mod_link', models.TextField(default='')),
                ('download_progress', models.IntegerField(default=0)),
                ('log', models.TextField(default='')),
                ('finish', models.IntegerField(default=0)),
            ],
        ),
    ]
