# Generated by Django 5.2 on 2025-06-05 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribetask',
            name='subscribe_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
