# Generated by Django 5.2 on 2025-04-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_manager', '0002_alter_subscribetask_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribetask',
            old_name='progress',
            new_name='download_progress',
        ),
        migrations.AddField(
            model_name='subscribetask',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='subscribetask',
            name='status',
            field=models.CharField(default='init', max_length=255),
        ),
    ]
