# Generated by Django 5.2 on 2025-04-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_manager', '0003_rename_progress_subscribetask_download_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribetask',
            name='download_progress',
            field=models.IntegerField(default=0),
        ),
    ]
