# Generated by Django 5.2 on 2025-04-18 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('stop_time', models.DateTimeField()),
            ],
        ),
    ]
