# Generated by Django 5.2 on 2025-04-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationinfo',
            name='stop_time',
            field=models.DateTimeField(null=True),
        ),
    ]
